Azure: Modify azure provisioner to use default credentials
confidential-containers/cloud-api-adaptor pull request #1017
Opened 2023-05-29 06:15 UTC by kartikjoshi21

Use default credentials to authenticate in azure go sdk, so that
it can choose what do authenticate from.
The order of authentication will be:
1. Environment variables
2. Managed identity
3. Azure cli auth

Also modify aks config to allow system assigned service principal in case of azure cli auth.

2023-05-29 15:06 UTC, surajssd requested changes
I still need to manually try it.

2023-05-29 15:06 UTC, surajssd commented on test/provisioner/provision_azure.properties
> +AZURE_CLI_AUTH="no"
let's stick to `true` and `false`?

2023-05-29 15:06 UTC, surajssd commented on test/provisioner/provision_azure_initializer.go
> +		log.Fatal(err)
return err?

2023-05-29 15:06 UTC, surajssd commented on test/provisioner/provision_azure_initializer.go
> +		return err
Add more context to the error.

2023-05-29 15:06 UTC, surajssd commented on test/provisioner/provision_azure_initializer.go
> +		return err
Add more context to the error.

2023-05-29 15:06 UTC, surajssd commented on test/provisioner/provision_azure_initializer.go
> +		log.Fatal(err)
Add more context to the error and return it?

2023-05-29 15:06 UTC, surajssd commented on test/provisioner/provision_azure.go
> +	Managedcluster := &armcontainerservice.ManagedCluster{
why is this variable capitalized?

2023-05-29 15:06 UTC, surajssd commented on test/provisioner/provision_azure_initializer.go
> +	if AzureProps.TenantID == "" {
This change should be in the previous commit?

2023-05-29 18:29 UTC, kartikjoshi21 commented on test/e2e/azure_test.go
> +	*/
It was removed in first commit and was again added in third one, as after  changing from compute to armcompute this code was not valid

2023-05-29 18:48 UTC, kartikjoshi21 commented on test/provisioner/provision_azure.go
> +	Managedcluster := &armcontainerservice.ManagedCluster{
not required.

2023-05-29 18:50 UTC, kartikjoshi21 commented on test/provisioner/provision_azure.go
> +		return err
its happening in previous step this is just to confirm deletion is done using response.Added context

2023-05-31 09:42 UTC, bpradipt approved these changes
/lgtm
Although I didn't get time to test this.

2023-06-03 23:51 UTC, surajssd approved these changes

2023-06-03 23:51 UTC, merged