ibmcloud: e2e Test cases for ibmcloud to check Peer Pod Logs Working Directory from container
confidential-containers/cloud-api-adaptor pull request #1046
Opened 2023-06-06 09:06 UTC by sudharshanibm3

Fixes: #1045 
Note: Current PR is dependent on two PR - #942 & #1002

2023-06-16 10:56 UTC, stevenhorsman commented
Can you add more information into the commit body please - e.g. what the test case is trying to cover. The idea should be that someone looking at the code can see why the change was made without having to check the issue

2023-06-16 10:59 UTC, stevenhorsman commented
Also - this code needs rebasing I think as it has code in that has already been merged.

2023-06-20 14:09 UTC, stevenhorsman requested changes

2023-06-20 15:29 UTC, sudharshanibm3 commented
Hi @stevenhorsman ,
Updated the code and resolved the code conflicts now

2023-06-20 15:49 UTC, stevenhorsman approved these changes
LGTM. Thanks!

2023-06-20 15:50 UTC, stevenhorsman commented
> LGTM. Thanks!

Just to check - where you able to test it manually yourself? `testimages:testworkdir` hasn't been built yet, so I can't check it.

2023-06-20 16:20 UTC, sudharshanibm3 commented
Hi @stevenhorsman ,
I ran the test cases with the image built in my registry `quay.io/sudharshanibm3/test-images:testworkdir`

```
=== RUN   TestCreatePeerPodAndCheckWorkDirLogs
=== RUN   TestCreatePeerPodAndCheckWorkDirLogs/WorkDirPeerPod_test
=== RUN   TestCreatePeerPodAndCheckWorkDirLogs/WorkDirPeerPod_test/Peer_pod_with_work_directory_has_been_created
    common_suite_test.go:168: Log output of peer pod:/other
time="2023-06-20T21:48:41+05:30" level=info msg="Deleting pod... workdirpod"
--- PASS: TestCreatePeerPodAndCheckWorkDirLogs (31.56s)
    --- PASS: TestCreatePeerPodAndCheckWorkDirLogs/WorkDirPeerPod_test (31.56s)
        --- PASS: TestCreatePeerPodAndCheckWorkDirLogs/WorkDirPeerPod_test/Peer_pod_with_work_directory_has_been_created (0.65s)
PASS
ok      github.com/confidential-containers/cloud-api-adaptor/test/e2e   96.580s
```

2023-06-20 16:24 UTC, sudharshanibm3 commented
Also I added `ImagePullPolicy` to `Always` in order to avoid reusing the cache image from container

```
Containers: []corev1.Container{{Name: containerName, Image: imageName, ImagePullPolicy: corev1.PullAlways}},
```

2023-06-21 13:54 UTC, mattarnoatibm approved these changes
LGTM

2023-06-21 13:56 UTC, Jordan9500 approved these changes
LGTM!

2023-06-21 13:59 UTC, merged