volume/csi-wrapper: update README doc and fix patch
confidential-containers/cloud-api-adaptor pull request #1078
Opened 2023-06-13 07:53 UTC by genjuro214

- still need update csi driver image tags

fixes #1042

2023-06-13 08:57 UTC, liudalibj approved these changes
LGTM, thanks @genjuro214

2023-06-13 08:58 UTC, liudalibj commented on volumes/csi-wrapper/README.md
>  1. Create the PeerpodVolume CRD object
L140, should remove `volumes/csi-wrapper/`

2023-06-13 08:59 UTC, liudalibj requested changes
L140, should remove volumes/csi-wrapper/

2023-06-14 03:19 UTC, liudalibj approved these changes
LGTM

2023-06-16 02:38 UTC, huoqifeng approved these changes
/lgtm

2023-06-16 02:38 UTC, merged