Azure: Remove vnet creation dependency from provisioner
confidential-containers/cloud-api-adaptor pull request #1222
Opened 2023-07-20 10:01 UTC by kartikjoshi21

Use default vnet and fetch defaut vnet subnet id in azure provisioner

Fixes: #1221

2023-07-20 14:14 UTC, surajssd requested changes

2023-07-20 14:14 UTC, surajssd commented on test/provisioner/provision_azure.go
> +		return fmt.Errorf("Failed to get AKS cluster: %q details: %w", AzureProps.ClusterName, err)
```suggestion
		return fmt.Errorf("getting AKS cluster object %q: %w", AzureProps.ClusterName, err)
```

2023-07-20 14:14 UTC, surajssd commented on test/provisioner/provision_azure.go
> +			return fmt.Errorf("Failed to get vnets associated with aks cluster: %q details: %w", AzureProps.ClusterName, err)
```suggestion
			return fmt.Errorf("getting VNETs of AKS cluster: %q: %w", AzureProps.ClusterName, err)
```

2023-07-20 14:14 UTC, surajssd commented on test/provisioner/provision_azure.go
> +		return fmt.Errorf("failed to fetch vnet: %q: %v", vnetName, err)
```suggestion
		return fmt.Errorf("fetching VNET: %q: %w", vnetName, err)
```

2023-07-20 14:14 UTC, surajssd commented on test/provisioner/provision_azure.go
> +		return fmt.Errorf("No subnets found in the specified vnet: %q: %v", vnetName, err)
```suggestion
		return fmt.Errorf("no subnet found in the specified VNET: %q", vnetName)
```

2023-07-20 14:14 UTC, surajssd commented on test/provisioner/provision_azure.go
> +	aks_rg := *cluster.Properties.NodeResourceGroup
Can't we get this from the existing AKS object? Or we can always generate this name, thus reducing the number of calls that happen to Azure API. 

https://learn.microsoft.com/en-us/azure/aks/faq#why-are-two-resource-groups-created-with-aks

2023-07-25 21:51 UTC, surajssd approved these changes

2023-07-26 09:40 UTC, bpradipt approved these changes
/lgtm
Thanks @kartikjoshi21

2023-07-26 09:42 UTC, mkulke approved these changes
lgtm

2023-07-26 09:54 UTC, merged