deps: update golang to 1.21.4
confidential-containers/cloud-api-adaptor pull request #1566
Opened 2023-11-09 07:47 UTC by lysliu

Bump golang from 1.20.10 to 1.21.4

Fixes: #1565

2023-11-09 08:12 UTC, huoqifeng commented
I'm not sure whether we're ready to upgrade to 1.21 yet, I guess a more safe approach is to update to `go1.20.11`.

2023-11-10 02:49 UTC, liudalibj approved these changes
LGTM

2023-11-10 02:52 UTC, liudalibj requested changes
please use `hack/update-go-container.sh` to update the version.

2023-11-10 02:54 UTC, liudalibj commented on hack/Dockerfile.golang
>  ARG GO_LINUX_ARM64_SHA256=fb3c7e15fc4413c5b81eb9f26dbd7cd4faedd5c720b30fa8e2ff77457f74cab6
these SHA256 hash need be updated too, please use `hack/update-go-container.sh`

2023-11-10 04:48 UTC, lysliu commented
> I'm not sure whether we're ready to upgrade to 1.21 yet, I guess a more safe approach is to update to `go1.20.11`.

Thanks, actually `1.21.4` failed some testcase, and `go1.20.11` also fixed the Vulnerability https://github.com/confidential-containers/cloud-api-adaptor/pull/1: GO-2023-2186.

2023-11-10 05:13 UTC, liudalibj approved these changes
LGTM

2023-11-10 05:29 UTC, genjuro214 approved these changes
LGTM

2023-11-10 05:30 UTC, merged