SecureComms: Fix needed following changes in other components
confidential-containers/cloud-api-adaptor pull request #2073
Opened 2024-09-30 10:11 UTC by davidhadas

Change the trustee operator namespace 
Add necessary initData to get SecureComms to work

2024-10-08 04:23 UTC, davidhadas commented
cc: @bpradipt

2024-10-08 14:14 UTC, stevenhorsman requested changes

2024-10-08 14:14 UTC, stevenhorsman commented on src/cloud-api-adaptor/docs/SecureComms.md
> +'''
This change doesn't belong in this PR?

2024-10-08 16:37 UTC, davidhadas commented on src/cloud-api-adaptor/docs/SecureComms.md
> +'''
Tnx, removing

2024-10-09 13:34 UTC, stevenhorsman commented
I've tried to test this code change and doc (creating CAA image quay.io/stevenhorsman/cloud-api-adaptor:dev-3fa7867a7499f2a636179f83c68174330812113d-dirty and podvm quay.io/stevenhorsman/podvm-generic-ubuntu-amd64:80da436ca39f40d439da987a3c83271f9dffb0ae3ac5dc9283a7ce8d6a112c97) and it doesn't work for me.

The agent proxy never connected and times out after 5mins:
```
2024/10/09 13:33:19 [adaptor/proxy] Retrying agent proxy connection to 192.168.122.33:15150...
2024/10/09 13:33:24 [adaptor/proxy] Retrying agent proxy connection to 192.168.122.33:15150...
2024/10/09 13:33:24 [adaptor/cloud] Error: start instance interrupted (context canceled). Cleaning up...
```

Has anyone else successfully tested this - and tips for what I did wrong here?

2024-10-09 15:00 UTC, davidhadas commented
Did you follow the instructions to activate secure comms in SecureComms.md?
The Caa in your envirinment is not configured to activate SecureComms. You
can see this since it is approaching 192.168.122.33:15150. When the peerpod
cm is configured correctly, caa shoumd approach 192.168.122.33:2222 instead

On Wed, 9 Oct 2024, 16:34 Steve Horsman, ***@***.***> wrote:

> I've tried to test this code change and doc (creating CAA image
> quay.io/stevenhorsman/cloud-api-adaptor:dev-3fa7867a7499f2a636179f83c68174330812113d-dirty
> and podvm
> quay.io/stevenhorsman/podvm-generic-ubuntu-amd64:80da436ca39f40d439da987a3c83271f9dffb0ae3ac5dc9283a7ce8d6a112c97)
> and it doesn't work for me.
>
> The agent proxy never connected and times out after 5mins:
>
> 2024/10/09 13:33:19 [adaptor/proxy] Retrying agent proxy connection to 192.168.122.33:15150...
> 2024/10/09 13:33:24 [adaptor/proxy] Retrying agent proxy connection to 192.168.122.33:15150...
> 2024/10/09 13:33:24 [adaptor/cloud] Error: start instance interrupted (context canceled). Cleaning up...
>
> Has anyone else successfully tested this - and tips for what I did wrong
> here?
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/confidential-containers/cloud-api-adaptor/pull/2073#issuecomment-2402367426>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ABAJMYLVD33OGEZ3CEEMF23Z2UWIDAVCNFSM6AAAAABPC52FOKVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMZDIMBSGM3DONBSGY>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***
> com>
>

2024-10-09 15:28 UTC, stevenhorsman commented
Ok, I've got it working. The doc doesn't mention that after editing `peer-pods-cm`, the changes don't come into effect until the CAA ds re-starts, so when I deleted the pod and the deployment re-created it it started working. Here is my CAA log for verification:
```
2024/10/09 15:24:44 [adaptor/cloud/libvirt] Creating VM 'podvm-nginx-75d4ffc6d9-6dhgb-8b317899'
2024/10/09 15:24:44 [adaptor/cloud/libvirt] Starting VM 'podvm-nginx-75d4ffc6d9-6dhgb-8b317899'
2024/10/09 15:24:45 [adaptor/cloud/libvirt] VM id 32
2024/10/09 15:25:06 [adaptor/cloud/libvirt] Instance created successfully
2024/10/09 15:25:06 [adaptor/cloud/libvirt] created an instance podvm-nginx-75d4ffc6d9-6dhgb-8b317899 for sandbox 8b31789990572e47f30b4c5178af0b3f7ed2f3b90f26537e3569d1377987e7a9
2024/10/09 15:25:06 [util/k8sops] nginx-75d4ffc6d9-6dhgb is now owning a PeerPod object
2024/10/09 15:25:06 [adaptor/cloud] created an instance podvm-nginx-75d4ffc6d9-6dhgb-8b317899 for sandbox 8b31789990572e47f30b4c5178af0b3f7ed2f3b90f26537e3569d1377987e7a9
2024/10/09 15:25:06 [secure-comms] InitPP read/create PP secret named: pp-8b31789990572e47f30b4c5178af0b3f7ed2f3b90f26537e3569d1377987e7a9
2024/10/09 15:25:07 [secure-comms] CreateSecret 'pp-8b31789990572e47f30b4c5178af0b3f7ed2f3b90f26537e3569d1377987e7a9'
2024/10/09 15:25:07 [secure-comms] Updating KBS with secret for: default/pp-8b31789990572e47f30b4c5178af0b3f7ed2f3b90f26537e3569d1377987e7a9/privateKey
2024/10/09 15:25:07 [secure-comms] Inbound listening to port 45973
2024/10/09 15:25:07 [secure-comms] Attestation phase: starting
2024/10/09 15:25:07 [secure-comms] Attestation phase: unable to Dial 192.168.122.245:2222: dial tcp 192.168.122.245:2222: connect: connection refused
...
2024/10/09 15:26:03 [secure-comms] Attestation phase: unable to Dial 192.168.122.245:2222: dial tcp 192.168.122.245:2222: connect: connection refused
2024/10/09 15:26:08 [secure-comms] Attestation phase: ssh connected - 192.168.122.245:2222
2024/10/09 15:26:09 [secure-comms] Attestation phase: ssh skipped validating server's host key (type ssh-rsa) during attestation
2024/10/09 15:26:09 [secure-comms] Attestation phase: peer reported phase Attestation
2024/10/09 15:26:10 [secure-comms] Attestation phase: NewSshPeer - peer requested a tunnel channel for KBS
2024/10/09 15:26:10 [secure-comms] Outbound KBS acceptProxy setting up for sid 8b31789990572e47f30b4c5178af0b3f7ed2f3b90f26537e3569d1377987e7a9
2024/10/09 15:26:10 [secure-comms] Outbound KBS acceptProxy modified URL to /kbs/v0/auth of host kbs-service.trustee-operator-system:8080
2024/10/09 15:26:10 [secure-comms] Outbound KBS acceptProxy to /kbs/v0/auth status code 200
2024/10/09 15:26:10 [secure-comms] Outbound KBS acceptProxy modified URL to /kbs/v0/attest of host kbs-service.trustee-operator-system:8080
2024/10/09 15:26:10 [secure-comms] Outbound KBS acceptProxy to /kbs/v0/attest status code 200
2024/10/09 15:26:10 [secure-comms] Outbound KBS acceptProxy recovered: runtime error: invalid memory address or nil pointer dereference
2024/10/09 15:26:10 [secure-comms] Attestation phase: NewSshPeer - peer requested a tunnel channel for KBS
2024/10/09 15:26:10 [secure-comms] Outbound KBS acceptProxy setting up for sid 8b31789990572e47f30b4c5178af0b3f7ed2f3b90f26537e3569d1377987e7a9
2024/10/09 15:26:10 [secure-comms] Outbound KBS acceptProxy modified URL to /kbs/v0/resource/default/sshclient/publicKey of host kbs-service.trustee-operator-system:8080
2024/10/09 15:26:10 [secure-comms] Outbound KBS acceptProxy to /kbs/v0/resource/default/sshclient/publicKey status code 200
2024/10/09 15:26:10 [secure-comms] Outbound KBS acceptProxy modified URL to /kbs/v0/resource/default/pp-8b31789990572e47f30b4c5178af0b3f7ed2f3b90f26537e3569d1377987e7a9/privateKey of host kbs-service.trustee-operator-system:8080
2024/10/09 15:26:10 [secure-comms] Outbound KBS acceptProxy to /kbs/v0/resource/default/pp-8b31789990572e47f30b4c5178af0b3f7ed2f3b90f26537e3569d1377987e7a9/privateKey status code 200
2024/10/09 15:26:10 [secure-comms] Attestation phase: peer reported it is upgrading to Kubernetes phase
2024/10/09 15:26:10 [secure-comms] Attestation phase: peer done by >>> chans closed <<<
2024/10/09 15:26:10 [secure-comms] Outbound KBS acceptProxy recovered: runtime error: invalid memory address or nil pointer dereference
2024/10/09 15:26:10 [secure-comms] Attestation phase: done
2024/10/09 15:26:10 [secure-comms] Kubernetes phase: starting (number of restarts 0)
2024/10/09 15:26:10 [secure-comms] Kubernetes phase: ssh connected - 192.168.122.245:2222
2024/10/09 15:26:10 [secure-comms] Kubernetes phase: ssh host key match - ssh-rsa
2024/10/09 15:26:10 [tunneler/vxlan] vxlan ppvxlan1 (remote 192.168.122.245:4789, id: 555001) created at /proc/1/task/12/ns/net
2024/10/09 15:26:10 [tunneler/vxlan] vxlan ppvxlan1 created at /proc/1/task/12/ns/net
2024/10/09 15:26:10 [secure-comms] Kubernetes phase: peer reported phase Kubernetes
2024/10/09 15:26:10 [secure-comms] Kubernetes phase: AddInbound: KATAAGENT
2024/10/09 15:26:10 [tunneler/vxlan] vxlan ppvxlan1 is moved to /var/run/netns/cni-c88622dc-b921-585c-2201-119b355563ff
2024/10/09 15:26:10 [tunneler/vxlan] Add tc redirect filters between eth0 and vxlan1 on pod network namespace /var/run/netns/cni-c88622dc-b921-585c-2201-119b355563ff
2024/10/09 15:26:10 [adaptor/proxy] Listening on /run/peerpod/pods/8b31789990572e47f30b4c5178af0b3f7ed2f3b90f26537e3569d1377987e7a9/agent.ttrpc
2024/10/09 15:26:10 [adaptor/proxy] Trying to establish agent proxy connection to 127.0.0.1:45973
2024/10/09 15:26:10 [adaptor/proxy] established agent proxy connection to 127.0.0.1:45973
2024/10/09 15:26:10 [secure-comms] Kubernetes phase: Inbound accept: KATAAGENT
2024/10/09 15:26:10 [adaptor/cloud] agent proxy is ready
2024/10/09 15:26:10 [secure-comms] Kubernetes phase: NewInboundInstance OpenChannel opening tunnel for: KATAAGENT
2024/10/09 15:26:10 [adaptor/proxy] CreateSandbox: hostname:nginx-75d4ffc6d9-6dhgb sandboxId:8b31789990572e47f30b4c5178af0b3f7ed2f3b90f26537e3569d1377987e7a9
2024/10/09 15:26:10 [adaptor/proxy]     storages:
2024/10/09 15:26:10 [adaptor/proxy]         mountpoint:/run/kata-containers/sandbox/shm source:shm fstype:tmpfs driver:ephemeral
2024/10/09 15:26:10 [adaptor/proxy] CreateContainer: containerID:8b31789990572e47f30b4c5178af0b3f7ed2f3b90f26537e3569d1377987e7a9
2024/10/09 15:26:10 [adaptor/proxy]     mounts:
2024/10/09 15:26:10 [adaptor/proxy]         destination:/proc source:proc type:proc
2024/10/09 15:26:10 [adaptor/proxy]         destination:/dev source:tmpfs type:tmpfs
2024/10/09 15:26:10 [adaptor/proxy]         destination:/dev/pts source:devpts type:devpts
2024/10/09 15:26:10 [adaptor/proxy]         destination:/dev/mqueue source:mqueue type:mqueue
2024/10/09 15:26:10 [adaptor/proxy]         destination:/sys source:sysfs type:sysfs
2024/10/09 15:26:10 [adaptor/proxy]         destination:/dev/shm source:/run/kata-containers/sandbox/shm type:bind
2024/10/09 15:26:10 [adaptor/proxy]         destination:/etc/resolv.conf source:/run/kata-containers/shared/containers/8b31789990572e47f30b4c5178af0b3f7ed2f3b90f26537e3569d1377987e7a9-0f87e1de521f68ee-resolv.conf type:bind
2024/10/09 15:26:10 [adaptor/proxy]     annotations:
2024/10/09 15:26:10 [adaptor/proxy]         io.katacontainers.pkg.oci.bundle_path: /run/containerd/io.containerd.runtime.v2.task/k8s.io/8b31789990572e47f30b4c5178af0b3f7ed2f3b90f26537e3569d1377987e7a9
2024/10/09 15:26:10 [adaptor/proxy]         io.kubernetes.cri.sandbox-memory: 0
2024/10/09 15:26:10 [adaptor/proxy]         io.kubernetes.cri.sandbox-cpu-quota: 0
2024/10/09 15:26:10 [adaptor/proxy]         io.kubernetes.cri.sandbox-cpu-shares: 2
2024/10/09 15:26:10 [adaptor/proxy]         io.kubernetes.cri.sandbox-id: 8b31789990572e47f30b4c5178af0b3f7ed2f3b90f26537e3569d1377987e7a9
2024/10/09 15:26:10 [adaptor/proxy]         io.kubernetes.cri.sandbox-namespace: default
2024/10/09 15:26:10 [adaptor/proxy]         io.kubernetes.cri.sandbox-cpu-period: 100000
2024/10/09 15:26:10 [ada [...]

2024-10-09 19:03 UTC, davidhadas commented
@stevenhorsman, 

SecureComms.md was now modified to include:
1. A comment that the deamonset should be reloaded after the ConfigMap changes. 
2. The extra detail showing the  trustee-operator secrets  after the trustee-operator install

2024-10-10 08:37 UTC, stevenhorsman approved these changes
LGTM and the doc fixes should resolve the issues I hit when testing this. Thanks @davidhadas!

2024-10-10 10:44 UTC, bpradipt approved these changes
/lgtm

2024-10-11 14:50 UTC, merged