all: Add Cross-build options for image binaries
confidential-containers/cloud-api-adaptor pull request #404
Opened 2022-12-05 11:19 UTC by jtumber-ibm

- Add GOOS/GOARCH setting
- Add RUST cross-compile options (CC/ARCH)

Fixes: #403

Holding until #396 has been merged so can do updates for building cross arch podvm images too.

Signed-off-by: James Tumber <james.tumber@ibm.com>

2023-01-05 16:00 UTC, Jordan9500 requested changes

2023-01-05 16:00 UTC, Jordan9500 commented on podvm/Makefile.inc
>  LIBC_ARCH := $(shell uname -m)
We should be able to remove these lines as `LIBC` is now defined above and uses `ARCH` instead.

2023-01-09 10:09 UTC, stevenhorsman approved these changes
LGTM.
This was the (slightly convoluted) testing I did to check this worked:
- Create a new x86 ibmcloud cluster with the IBM e2e process (in order to have a machine with all the required pre-reqs installed and configured)
- Logged into the x86 worker node
- Installed the extra s390x tools needed:
```
rustup target add s390x-unknown-linux-gnu
sudo apt-get install gcc-s390x-linux-gnu
```
- removed the x86 versions of the libseccomp caches built into the kata-agent directory with:
```
pushd  ~/kata-containers/src/agent
make clean
popd
```
(this can be done more surgically to remove the specific cache(s) for libsecomp)
- Deleted the CAA x86 version of the libsecomp binaries so the makefile can built them with s390x
```
cd cloud-api-adaptor/ibmcloud/image/
rm -rf staticlib/
```
- Built the binaries in s390x:
```
ARCH=s390x CLOUD_PROVIDER=ibmcloud make binaries
```
This looked like it all worked.

Whilst this looks a little messy with the libsecomp binaries and caches being deleted, this is just as I'm re-using a system that has previously build it for a different architecture. If it was built in a isolated environment like a container, or a automation controlled VM this shouldn't be an issue, so I'm happy with this work.
Thanks @jtumber-ibm for the PR and help with debugging!

2023-01-09 12:53 UTC, Jordan9500 approved these changes
LGTM! Following the same steps done by Steven above I was able to get a successful build going. 

Thank you @jtumber-ibm :)

2023-01-10 17:05 UTC, merged