ibmcloud | doc: Update ibmcloud doc to use operator approach
confidential-containers/cloud-api-adaptor pull request #679
Opened 2023-03-07 13:41 UTC by stevenhorsman

2023-03-09 09:44 UTC, Jordan9500 requested changes
LGTM Other than a few minor changes

2023-03-09 09:44 UTC, Jordan9500 commented on ibmcloud/README.md
> +[Delete the cluster documentation](./ibmcloud/cluster#delete-the-cluster) and then start again.
think this needs to be `./cluster#delete-the-cluster`

2023-03-09 12:42 UTC, stevenhorsman commented
@Jordan9500 - thanks so much for the review. I hope I've address your comment adequately, but please feel free to give further feedback. For convenience I've push the changes as a separate commit, but will squash it before merging.

2023-03-09 13:09 UTC, Jordan9500 approved these changes
LGTM! Thanks!

2023-03-10 16:58 UTC, jtumber-ibm approved these changes

2023-03-10 16:58 UTC, merged