Update node label prefix
confidential-containers/cloud-api-adaptor pull request #784
Opened 2023-04-03 05:34 UTC by kartikjoshi21

Update node label from node-role.kubernetes.io to node.kubernetes.io

Fixes: #780

2023-04-03 12:56 UTC, bpradipt reviewed
Overall this lgtm. It's a simple change.
However one thing which I'm unsure is whether we need to make changes to the CoCo operator as well.
@wainersm @stevenhorsman ?

2023-04-05 08:35 UTC, kartikjoshi21 commented
> Overall this lgtm. It's a simple change. However one thing which I'm unsure is whether we need to make changes to the CoCo operator as well. @wainersm @stevenhorsman ?

Yess looks like it need to be changed in operator repo as well. Some places are not related to this but its always good to be on latest KUBE version norms. I will submit a PR in that repo as well

2023-04-05 09:39 UTC, kartikjoshi21 commented
> Yess looks like it need to be changed in operator repo as well. Some places are not related to this but its always good to be on latest KUBE version norms. I will submit a PR in that repo as well

https://github.com/confidential-containers/operator/pull/195 added this PR In operator repo

2023-04-10 06:06 UTC, kartikjoshi21 commented
@surajssd  @bpradipt Can we plan to review and merge this and corresponding operator one tagged in this PR ?

2023-04-10 17:40 UTC, surajssd commented on test/provisioner/provision_azure.go
> +	// Update this to use label wile provisioning cluster
```suggestion
	// Update this to use label while provisioning cluster
```

nit: 😉

2023-04-10 17:40 UTC, surajssd commented
The tests on the operator are failing for some reason. IMO both of these should be merged at the same time.

2023-04-11 14:53 UTC, kartikjoshi21 commented
> The tests on the operator are failing for some reason. IMO both of these should be merged at the same time.

Yes, iam not able to open the failing reason in that ci. Looks like these two needs to be merged together.

2023-04-11 17:49 UTC, kartikjoshi21 commented
> @kartikjoshi21 mind to wait this change get merged into confidential-containers/operator first?

Added hold label until we get operator one merged. Thanks

2023-07-10 15:52 UTC, stevenhorsman commented
@kartikjoshi21 - The CoCo version has been merge merged now, and this is quite old, so can you rebase and we can try and get this side in soon? Thanks

2023-07-11 10:47 UTC, stevenhorsman requested changes

2023-07-11 10:47 UTC, stevenhorsman commented on install/yamls/ccruntime-peer-pods.yaml
This file shouldn't have been re-added

2023-07-11 10:48 UTC, kartikjoshi21 commented on install/yamls/ccruntime-peer-pods.yaml
Updated in last commit

2023-07-11 11:34 UTC, stevenhorsman approved these changes
LGTM and I've tried it out locally and it resolves the problems we have with mismatch between CAA code and the upstream coco operator. Thanks

2023-07-11 12:23 UTC, bpradipt approved these changes
/lgtm
Thanks @kartikjoshi21

2023-07-11 12:24 UTC, merged

2023-07-17 15:38 UTC, wainersm commented
@stevenhorsman what version of the cloud-api-adaptor image have you used to test this change?

I just ran the libvirt e2e tests on my machine and the latest image (`quay.io/confidential-containers/cloud-api-adaptor:latest`) is still requiring the old label:

```
[wmoschet@wainer-laptop cloud-api-adaptor]$ kubectl get ds -n confidential-containers-system
NAME                             DESIRED   CURRENT   READY   UP-TO-DATE   AVAILABLE   NODE SELECTOR                            AGE
cc-operator-daemon-install       1         1         1       1            1           node.kubernetes.io/worker=               12m
cc-operator-daemon-uninstall     0         0         0       0            0           katacontainers.io/kata-runtime=cleanup   13m
cc-operator-pre-install-daemon   1         1         1       1            1           node.kubernetes.io/worker=               13m
cloud-api-adaptor-daemonset      0         0         0       0            0           node-role.kubernetes.io/worker=          13m
```

2023-07-17 15:40 UTC, wainersm commented
> @stevenhorsman what version of the cloud-api-adaptor image have you used to test this change?
> 
> I just ran the libvirt e2e tests on my machine and the latest image (`quay.io/confidential-containers/cloud-api-adaptor:latest`) is still requiring the old label:
> 
> ```
> [wmoschet@wainer-laptop cloud-api-adaptor]$ kubectl get ds -n confidential-containers-system
> NAME                             DESIRED   CURRENT   READY   UP-TO-DATE   AVAILABLE   NODE SELECTOR                            AGE
> cc-operator-daemon-install       1         1         1       1            1           node.kubernetes.io/worker=               12m
> cc-operator-daemon-uninstall     0         0         0       0            0           katacontainers.io/kata-runtime=cleanup   13m
> cc-operator-pre-install-daemon   1         1         1       1            1           node.kubernetes.io/worker=               13m
> cloud-api-adaptor-daemonset      0         0         0       0            0           node-role.kubernetes.io/worker=          13m
> ```

Never mind, the branch I was working one is outdated.