Azure: parameterize ssh user name
confidential-containers/cloud-api-adaptor pull request #791
Opened 2023-04-03 20:01 UTC by kartikjoshi21

change default value of ssh user name to peerpod and parameterize it in case user wants to provide custom name

Fixes: #717

2023-04-04 15:14 UTC, surajssd reviewed
Right now this is exposed at the flag level, but this should bubble up as an env var to the kustomization file here: https://github.com/confidential-containers/cloud-api-adaptor/blob/53201a825540127507e1d2a390eb8b40e379ef67/install/overlays/azure/kustomization.yaml#L19, isn't it?

2023-04-06 03:33 UTC, knrt10 approved these changes

2023-04-10 17:45 UTC, surajssd commented
I think this is still missing changing the username at the packer level.

2023-04-11 17:43 UTC, surajssd requested changes
I build a new image and tried deploying it but it still uses older username:

```bash
# ssh -i /tmp/key peerpod@10.2.0.5
Warning: Permanently added '10.2.0.5' (ED25519) to the list of known hosts.
peerpod@10.2.0.5: Permission denied (publickey).

# ssh -i /tmp/key ubuntu@10.2.0.5
Welcome to Ubuntu 22.04.2 LTS (GNU/Linux 5.15.0-1035-azure x86_64)

...

ubuntu@podvm-nginx-86fcc9854-8cjzx-9046ce1c:~$ ps aufx | grep nginx
1001         799  0.0  0.0  24172  5472 ?        S    17:34   0:00  \_ nginx: master process /opt/bitnami/nginx/sbin/nginx -c /opt/bitnami/nginx/conf/nginx.conf -g daemon off;
1001         823  0.0  0.0  24612  2436 ?        S    17:34   0:00      \_ nginx: worker process
1001         824  0.0  0.0  24612  2436 ?        S    17:34   0:00      \_ nginx: worker process
1001         825  0.0  0.0  24612  2436 ?        S    17:34   0:00      \_ nginx: worker process
1001         826  0.0  0.0  24612  2436 ?        S    17:34   0:00      \_ nginx: worker process
1001         827  0.0  0.0  24612  2436 ?        S    17:34   0:00      \_ nginx: worker process
1001         828  0.0  0.0  24612  2436 ?        S    17:34   0:00      \_ nginx: worker process
1001         829  0.0  0.0  24612  2436 ?        S    17:34   0:00      \_ nginx: worker process
1001         830  0.0  0.0  24612  2436 ?        S    17:34   0:00      \_ nginx: worker process
ubuntu       990  0.0  0.0   4020  2040 pts/0    S+   17:39   0:00              \_ grep --color=auto nginx
```

2023-04-17 10:36 UTC, kartikjoshi21 commented
**Test with default user peerpod**

```
root@security-context-demo:/# ssh -i id_rsa 10.2.0.8
The authenticity of host '10.2.0.8 (10.2.0.8)' can't be established.
ECDSA key fingerprint is SHA256:8CXyKnbfA5HDJbLrFcRhNDBDHu+ntpYszUMXqN8ExSU.
Are you sure you want to continue connecting (yes/no)? yes
Warning: Permanently added '10.2.0.8' (ECDSA) to the list of known hosts.
Enter passphrase for key 'id_rsa': 
Please login as the user "peerpod" rather than the user "root".

Connection to 10.2.0.8 closed.
root@security-context-demo:/# ssh -i id_rsa peerpod@10.2.0.8
Enter passphrase for key 'id_rsa': 
Welcome to Ubuntu 22.04.2 LTS (GNU/Linux 5.15.0-1035-azure x86_64)

 * Documentation:  https://help.ubuntu.com
 * Management:     https://landscape.canonical.com
 * Support:        https://ubuntu.com/advantage


This system has been minimized by removing packages and content that are
not required on a system that users do not log into.

To restore this content, you can run the 'unminimize' command.

Expanded Security Maintenance for Applications is not enabled.

0 updates can be applied immediately.

Enable ESM Apps to receive additional future security updates.
See https://ubuntu.com/esm or run: sudo pro status


The list of available updates is more than a week old.
To check for new updates run: sudo apt update

The programs included with the Ubuntu system are free software;
the exact distribution terms for each program are described in the
individual files in /usr/share/doc/*/copyright.

Ubuntu comes with ABSOLUTELY NO WARRANTY, to the extent permitted by
applicable law.

To run a command as administrator (user "root"), use "sudo <command>".
See "man sudo_root" for details.

peerpod@podvm-nginx-deployment-86fcc9854-5x4ks-bb784602:~$ 
```

**Test with username kartikjoshi**
export SSH_USERNAME=kartikjoshi
```
root@security-context-demo:/# ssh -i id_rsa 10.2.0.9
The authenticity of host '10.2.0.9 (10.2.0.9)' can't be established.
ECDSA key fingerprint is SHA256:Xk8wBBET/LoQXv+GxuhzgBbfvXYSHnL1MZVwiJmrZZg.
Are you sure you want to continue connecting (yes/no)? yes
Warning: Permanently added '10.2.0.9' (ECDSA) to the list of known hosts.
Enter passphrase for key 'id_rsa': 
Please login as the user "kartikjoshi" rather than the user "root".

Connection to 10.2.0.9 closed.
root@security-context-demo:/# ssh -i id_rsa kartikjoshi@10.2.0.9
Enter passphrase for key 'id_rsa': 
Welcome to Ubuntu 22.04.2 LTS (GNU/Linux 5.15.0-1035-azure x86_64)

 * Documentation:  https://help.ubuntu.com
 * Management:     https://landscape.canonical.com
 * Support:        https://ubuntu.com/advantage


This system has been minimized by removing packages and content that are
not required on a system that users do not log into.

To restore this content, you can run the 'unminimize' command.

Expanded Security Maintenance for Applications is not enabled.

0 updates can be applied immediately.

Enable ESM Apps to receive additional future security updates.
See https://ubuntu.com/esm or run: sudo pro status


The list of available updates is more than a week old.
To check for new updates run: sudo apt update

The programs included with the Ubuntu system are free software;
the exact distribution terms for each program are described in the
individual files in /usr/share/doc/*/copyright.

Ubuntu comes with ABSOLUTELY NO WARRANTY, to the extent permitted by
applicable law.

kartikjoshi@podvm-nginx-deployment-86fcc9854-ztr9w-c6516295:~$ 
```

2023-04-17 19:27 UTC, surajssd commented on azure/image/azure-ubuntu.pkr.hcl
> +      "sudo bash ~/create-user.sh ${var.ssh_username}"
```suggestion
      "sudo useradd -m -s /bin/bash ${var.ssh_username}"
```

2023-04-17 19:27 UTC, surajssd commented on azure/image/create-user.sh
> +sudo useradd -m -s /bin/bash "${ssh_username}"
```suggestion
```

2023-04-17 19:28 UTC, surajssd commented on azure/image/azure-ubuntu.pkr.hcl
> +      "sudo bash ~/create-user.sh ${var.ssh_username}"
I think for single liner we can skip using bash script.

2023-04-17 19:28 UTC, surajssd commented on azure/image/create-user.sh
> +sudo useradd -m -s /bin/bash "${ssh_username}"
IMHO the default username setting here is redundant it is already set in the packer variables file.

2023-04-17 20:02 UTC, surajssd approved these changes

2023-04-18 01:49 UTC, merged