Azure: Build peerpod vm image using packer with limited scope
confidential-containers/cloud-api-adaptor pull request #797
Opened 2023-04-06 07:56 UTC by kartikjoshi21

Update packer config to build pod vm image using resource group specific scope

2023-04-10 06:41 UTC, knrt10 approved these changes
+1

2023-04-10 17:36 UTC, surajssd requested changes

2023-04-10 17:36 UTC, surajssd commented on azure/README.md
> -export LOCATION="REPLACE_ME"
The subsequent command will fail to create resource group without providing location?

2023-04-10 17:36 UTC, surajssd commented on azure/README.md
> +  --scope /subscriptions/${SUBSCRIPTION_ID}/resourceGroups/${RESOURCE_GROUP}
```suggestion
az ad sp create-for-rbac \
    --name "Packer Build" \
    --role "Contributor" \
    --scopes /subscriptions/${SUBSCRIPTION_ID}/resourceGroups/${RESOURCE_GROUP} \
    --query "{ CLIENT_ID: appId, CLIENT_SECRET: password, TENANT_ID: tenant }"

az role assignment create \
  --assignee ${CLIENT_ID} \
  --role "Contributor" \
  --scope /subscriptions/${SUBSCRIPTION_ID}/resourceGroups/${RESOURCE_GROUP}
```

2023-04-10 17:36 UTC, surajssd commented on azure/README.md
> +  --scope /subscriptions/${SUBSCRIPTION_ID}/resourceGroups/${RESOURCE_GROUP}
Also the last command fails with the following error:

```bash
$ az role assignment create \
  --assignee ${CLIENT_ID} \
  --role "Contributor" \
  --scope /subscriptions/${SUBSCRIPTION_ID}/resourceGroups/${RESOURCE_GROUP}
argument --assignee: expected one argument
```

My guess is that `CLIENT_ID` is not populated, the new doc should mention where this `CLIENT_ID` is coming from.

2023-04-10 17:36 UTC, surajssd commented on azure/README.md
> +  --scope /subscriptions/${SUBSCRIPTION_ID}/resourceGroups/${RESOURCE_GROUP}
I think I will divide the above two commands with instructions between them to export respective environment variable.

2023-04-11 16:01 UTC, surajssd requested changes

2023-04-11 19:47 UTC, kartikjoshi21 commented on azure/README.md
> +The env var `CLIENT_ID`:`appId`, `CLIENT_SECRET`:`password`, `TENANT_ID`:`tenant` can be copied from the output of the last command:
This command actually gives all the things in appid, password and tenant format

2023-04-11 19:52 UTC, surajssd commented on azure/README.md
> +The env var `CLIENT_ID`:`appId`, `CLIENT_SECRET`:`password`, `TENANT_ID`:`tenant` can be copied from the output of the last command:
That's why I suggested this change:

```bash
az ad sp create-for-rbac \
    --name "Packer Build" \
    --role "Contributor" \
    --scopes /subscriptions/${SUBSCRIPTION_ID}/resourceGroups/${RESOURCE_GROUP} \
    --query "{ CLIENT_ID: appId, CLIENT_SECRET: password, TENANT_ID: tenant }"
```

That way the user does not have to do the manual translation.

2023-04-11 20:01 UTC, surajssd approved these changes

2023-04-12 07:12 UTC, merged